---
stages:
  - buildWar
  - deploy
  - buildDocker
  
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

buildWar:
  stage: buildWar
  script:
    - 'mvn $MAVEN_CLI_OPTS install -B '
  only:
    - master
  artifacts:
    paths:
    - target/staging
  image: maven:3.3.9-jdk-8


pages:
  image: busybox:latest
  stage: deploy
  script:
    - mkdir target
    - cp .m2/repository/com/ibm/icp/coc/db-stress-tester/1.0.0/db-stress-tester-1.0.0.war target/db-stress-tester.war
  dependencies:
    - buildWar
  artifacts:
    paths:
    - public
  only:
    - master
    
buildDocker:
  image: gitlab/dind:latest
  stage: buildDocker
  when: on_success
  dependencies:
    - pages
  only:
  - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/icp-coc-tools/db-stress-tester .
    - docker push registry.gitlab.com/icp-coc-tools/db-stress-tester


